// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/favicon.png",
    "/logo-01.png",
    "/logo-02.png",
    "/logo-03.png",
    "/weather-icons/01d@2x.png",
    "/weather-icons/01n@2x.png",
    "/weather-icons/02d@2x.png",
    "/weather-icons/02n@2x.png",
    "/weather-icons/03d@2x.png",
    "/weather-icons/03n@2x.png",
    "/weather-icons/04d@2x.png",
    "/weather-icons/04n@2x.png",
    "/weather-icons/09d@2x.png",
    "/weather-icons/09n@2x.png",
    "/weather-icons/10d@2x.png",
    "/weather-icons/10n@2x.png",
    "/weather-icons/11d@2x.png",
    "/weather-icons/11n@2x.png",
    "/weather-icons/13d@2x.png",
    "/weather-icons/13n@2x.png",
    "/weather-icons/50d@2x.png",
    "/weather-icons/50n@2x.png"
  ]
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/home/anibaw/Documents/qerja/ria-busana/sveltekit/.wrangler/tmp/pages-Sik1DJ/bundledWorker-0.8320960345253436.mjs";
import { isRoutingRuleMatch } from "/home/anibaw/Documents/qerja/ria-busana/sveltekit/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/home/anibaw/Documents/qerja/ria-busana/sveltekit/.wrangler/tmp/pages-Sik1DJ/bundledWorker-0.8320960345253436.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        if (worker.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return worker.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=w2b83gqvz8.js.map
